### ISSUE TITLE
Rename WithGzip to WithGzipSupport or remove altogether

### ISSUE THREAD

**Issue by bufdev** [bufbuild/connect-go#100]
When I see `WithGzip` in the generated code for clients, I think "all my requests are being gzipped". However, this is `WithGzipRequests`, which also confuses me a bit - `WithGzip` says "this allows request and responses to be gzipped", so I'd think that `WithGzipRequests` allows just requests, but this isn't the case obviously.

I'd also wonder if we should just remove `WithGzip` altogether and call gzip support something that is standard, and then rename `WithGzipRequests` to `WithGzip`.

**Comment by bufdev** [comment]
Probably something we should still do, but limit bikeshedding to 5 minutes

**Comment by akshayjshah** [comment]
moved to https://linear.app/bufbuild/issue/TCN-65/exported-identifier-renames
