### ISSUE TITLE
Update the names of the grpc-related structs and functions

### ISSUE THREAD

**Issue by bufdev** [bufbuild/connect-go#123]
`protocolGRPC` vs `grpcClient, grpcHandler`, etc - we probably should prefix with `grpc`, ie move to `grpcProtocol`.

Other related things:

- We should include grpc in all the grpc-related functions, ie `parseTimeout, statusFromError` etc
- Should we collapse the grpc-related files a bit? Not sure.
- should `protocol` be `clientProtocol, handlerProtocol`? Super nit, not important.

**Comment by bufdev** [comment]
@akshayjshah we don't need to do this full-on, but keeping in mind prefixing grpc-specific things with `grpc` when we do the grpc/connect protocol refactor

**Comment by akshayjshah** [comment]
Moved to https://linear.app/bufbuild/issue/TCN-65/misc-renaming
