### ISSUE TITLE
Look into not supporting the standard Golang protoc plugin options

### ISSUE THREAD

**Issue by bufdev** [bufbuild/connect-go#143]
I need to look into it again because I've just been setting `paths=source_relative` automatically, but do we want any other option than that? We might want to investigate not allowing other standard `protogen` options and effectively hard-fixing `paths=source_relative`, it kinda stinks that we have to tell people you should usually set an option.

**Comment by akshayjshah** [comment]
moved to https://linear.app/bufbuild/issue/TCN-67/drop-support-for-standard-go-protoc-plugin-options
