### ISSUE TITLE
Implement gRPC's standard interop tests

### ISSUE THREAD

**Issue by akshayjshah** [bufbuild/connect-go#24]
The first-party gRPC implementations have a standardized battery of interoperability tests. Many of them test particular flags or option schemes that may not apply to us, but let's see if we can get some useful test coverage from them.

https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md

**Comment by akshayjshah** [comment]
@doriable Can you update the status of this issue?

**Comment by doriable** [comment]
Yep, updated the check list above and starting a new one here for remaining work:

- [ ] Adding a cross test for propagating duplicate metadata keys
- [ ] Clean-up and documentation for running cross tests in CI
- [ ] Web interop tests: https://github.com/grpc/grpc-web/blob/master/doc/interop-test-descriptions.md

**Comment by akshayjshah** [comment]
Are we running the interop tests on a schedule? I'd really like the latest commit on `main` in connect-go run through the full interop testing suite daily.

**Comment by akshayjshah** [comment]
I'm going to call this done. We're running the interop tests, and they're passing - the rest of the cleanup can be tracked internally.
