### ISSUE TITLE
Random Compression Method Selection

### ISSUE THREAD

**Issue by klauspost** [bufbuild/connect-go#259]
Say you register 4 compression methods on both the handler and the client.

It seems like the server picks the first compression method it recognizes, unless a specific method was used when sending the request.

However, looking at the [client side](https://github.com/bufbuild/connect-go/blob/c35ee255c4f0265262da15a5f431d761a7498b93/compression.go#L160) the order the methods are sent is random since it collects names from a map.

As far as I can tell this makes it impossible to select an order of preference from the client side. Furthermore it appears to me that `gzip` cannot be removed from the pool, only replaced.

**Comment by klauspost** [comment]
FWIW, just added https://github.com/klauspost/connect-compress

**Comment by klauspost** [comment]
> We could just keep the preference order implied by option ordering, but that doesn't seem right either: gzip will usually be first, but anyone registering new compression algorithms would probably prefer something newer (maybe zstd or br).

Correct, but if you registered gzip again, I presume it would be last. You could also do it reverse, so last registered is preferred.

As an alternative a `WithCompressionOrder(names ...string) Option` could be added to ensure a specific order.

**Comment by akshayjshah** [comment]
> FWIW, just added https://github.com/klauspost/connect-compress

It's worth a lot, since writing that exact package is the next thing on my to-do list. Thank you! Also, thanks for everything you've done with `compress` - we talked for a bit on [compress#423](https://github.com/klauspost/compress/issues/423), and thanks to your input I ended up just adding `connect.CompressMinBytes`.

**Comment by klauspost** [comment]
> `connect.CompressMinBytes`

Yeah, that is the most important. 

My implementation will not care about pre-compressed content. stdlib gzip is very bad at that. Compare 62MB/s (stdlib gzip) to 4665MB/s (alt gzip).

**Comment by klauspost** [comment]
If you want to "adopt" the package let me know. I won't feel bad about archiving it and redirecting to yours.

**Comment by akshayjshah** [comment]
> If you want to "adopt" the package let me know. I won't feel bad about archiving it and redirecting to yours.

Definitely not! You're the authority, and we all very much appreciate you looking at `connect-go` so closely and writing an integration package. If it's okay with you, I was going to add some references to your package in the Connect documentation.

**Comment by klauspost** [comment]
Added performance and made an `0.1.0` release.

> Definitely not!

I was more thinking that it might have higher adoption, if it was a package "under your wings". I assume you don't want the dependencies in your main package.

>  If it's okay with you, I was going to add some references to your package in the Connect documentation.

Of course, go ahead. I only have extremely lightweight tests using your "ping" example. I don't know if you have some more complex interactions I can test.

**Comment by bufdev** [comment]
@klauspost would you be open to PRs on connect-compress with a few suggested changes? Let me know, I can just put some up and you can accept or reject as you wish if so.

**Comment by klauspost** [comment]
Of course. Especially tests would be awesome!

**Comment by akshayjshah** [comment]
@klauspost Just landed a PR so that the last registered compressor is the most preferred. We'll also update the Connect protocol specification to match (we don't control the gRPC specification, but this seems like reasonable behavior there too.)

The fix will go out with v0.1.1, which we should tag soon.
