### ISSUE TITLE
More request information in Interceptor.WrapStreamContext()

### ISSUE THREAD

**Issue by anzboi** [bufbuild/connect-go#296]
Currently there is no way to enrich a stream context with information about the request. The `WrapStreamContext()` method only accepts a parent context and does not give us any information about the request.

In particular, we need access to the endpoint spec and request headers.

Our primary use case for this is authentication, where we would like to be able to apply some generic token parsing and validation logic to all requests, and enrich context with authentication info.

**Comment by deepankarjha** [comment]
Same here!
Currently struggling with writing the streaming interceptor which can modify request headers to add some additional info for the downstream handlers. Mainly for authentication of JWT and then passing on the authenticated userID to the downstream handlers. 

Unary interceptors work but couldn't find a way to do that with streaming interceptors.

**Comment by deepankarjha** [comment]
Is the context passed in WrapStreamContext(), WrapStreamSender(), and WrapStreamReceiver() interface methods request scoped or global context? 
Just want to avoid situations to mix information of 2 different client requests.

**Comment by akshayjshah** [comment]
Hi @deepankarjha! The context is request-scoped.

I'm on vacation for a few days, but I'll respond to this issue in detail early next week.

**Comment by deepankarjha** [comment]
> Hi @deepankarjha! The context is request-scoped.
> 
> I'm on vacation for a few days, but I'll respond to this issue in detail early next week.

@akshayjshah any updates on this?

**Comment by akshayjshah** [comment]
I'm exploring a few different options for updating the interceptor interface. I think I've found something promising, but I'd like to make sure we've gotten it right before making a breaking change. I'll have a PR open next week for you and @anzboi to look at.

**Comment by akshayjshah** [comment]
We'll ship #316 as part of the next release, probably by end of week. I'd like to ship an interceptor to recover panics as part of that release - it's broadly useful and a good example of implementing the `Interceptor` API.

**Comment by akshayjshah** [comment]
Perfect! Lucky coincidence :)
