### ISSUE TITLE
Warnings when running on Windows

### ISSUE THREAD

**Issue by kohenkatz** [bufbuild/connect-go#297]
When using this tool on Windows, I get the following warning when I run `buf generate`:

```
Warning: Generated file name "live\\v1\\livev1connect\\events_service.connect.go" does not conform to the Protobuf generation specification.
Note that the file name must be relative, use "/" instead  of "\", and not use "." or ".." as part of the file name.
Buf will continue without error here, but please raise an issue with the maintainer of the plugin and reference
https://github.com/protocolbuffers/protobuf/blob/95e6c5b4746dd7474d540ce4fb375e3f79a086f8/src/google/protobuf/compiler/plugin.proto#L122
```

As far as I can tell, the problem comes from this line:

https://github.com/bufbuild/connect-go/blob/ae60446db6d1a5f7353bfb450b2bc7edfe095e2b/cmd/protoc-gen-connect-go/main.go#L105

`filepath.Join` uses an OS-specific path separator, but `buf` expects Unix-style path separators even on Windows.

I think that this can be fixed by changing from `filepath.Join` to plain `path.Join`, but I don't know the code in this repo well enough to be sure that's all that needs to be changed.

**Comment by bufdev** [comment]
Good catch, and thanks for filing! You are correct, that should be path.Join. We will get it fixed.
