### ISSUE TITLE
Are there plans to provide a standalone prometheus package that works with connect-go?

### ISSUE THREAD

**Issue by nomad-software** [bufbuild/connect-go#314]
**Is your feature request related to a problem? Please describe.**
Nope. This isn't directly related to connect-go per se but to other packages made available by bufbuild.

I notice there is a standalone package to implement [health checking](https://github.com/bufbuild/connect-grpchealth-go) so I wondered if there were plans to also release a Prometheus package that imitates https://github.com/grpc-ecosystem/go-grpc-prometheus but is created to work with connect-go?

**Describe the solution you'd like**
A drop-in solution similar to https://github.com/bufbuild/connect-grpchealth-go that mimics https://github.com/grpc-ecosystem/go-grpc-prometheus

**Describe alternatives you've considered**
I'd have to write one myself, which is fine but I wondered if you have plans for a more official package?

**Comment by akshayjshah** [comment]
Sorry! We're caught up with the upcoming `connect-web` release. We'll return to OC integration once that's done.

**Comment by akshayjshah** [comment]
Sorry for the long periods of silence on this issue! Internally, we've decided to switch from OpenCensus to OpenTelemetry 😰  We're still not planning to write a first-party package that integrates directly with Prometheus. I'm going to close this issue in favor of #344 - if you're interested in ready-to-use observability interceptors, please subscribe to that issue instead.

**Comment by pqn** [comment]
https://github.com/easyCZ/connect-go-prometheus may be relevant here.
