### ISSUE TITLE
Listening on a unix socket?

### ISSUE THREAD

**Issue by frantjc** [bufbuild/connect-go#323]
examples in the documentation clearly demonstrate how to listen on a port:

```go
func main() {
  mux := http.NewServeMux()
  mux.Handle(pingv1connect.NewPingServiceHandler(&PingServer{}))
  log.Fatal(
    http.ListenAndServe(
      "localhost:8080",
      h2c.NewHandler(mux, &http2.Server{}),
    )
  )
}
```

but I have been unable to find an example for listening on a unix socket e.g. `unix:///var/run/buildkitd.sock` as is common with gRPC daemons. Is it possible? Is there documentation detailing how anywhere?

Thanks!

**Comment by akshayjshah** [comment]
Hey @frantjc! Yes, this is definitely possible. It works just as it would for any other `net/http` server:

```go
func main() {
  mux := http.NewServeMux()
  mux.Handle(pingv1connect.NewPingServiceHandler(&PingServer{}))
  server := &http.Server{Handler: h2c.NewHandler(mux, &http2.Server{})}
  socket, err := net.Listen("unix", "/path/to/socket")
  if err != nil {
    log.Fatal(err)
  }
  log.Fatal(server.Serve(socket))
}
```

As usual for `net/http`, the client side is a bit more complex. You may want to use something like https://github.com/peterbourgon/unixtransport - once you have a properly-configured `*http.Client`, you can use it with `connect-go` and a base URL that has the `https+unix` scheme.

**Comment by frantjc** [comment]
Thanks for the helpful response and the resources to look into. Before I go off and give it a try, just want to clarify what the the address would look like. Does this look about right?

http+unix:///var/run/my.sock

**Comment by akshayjshah** [comment]
It depends on how you write your `http.Transport` (or which third-party package you use). You need some way to distinguish these two cases:

* socket `/var/run/sock` with HTTP path `/demo`
* socket `/var/run` with HTTP path `/sock/demo`

https://github.com/peterbourgon/unixtransport uses a colon, so your address would be `http+unix:///var/run/my.sock:`.

**Comment by akshayjshah** [comment]
I'm going to close this as fixed, @frantjc! Hope this is all working out okay for you.
