### ISSUE TITLE
SendMaxBytes config option

### ISSUE THREAD

**Issue by mattrobenolt** [bufbuild/connect-go#330]
In https://github.com/bufbuild/connect-go/pull/311, a ReadMaxBytes option was added, but to go along with that, when you control both the client and server, an equivalent SendMaxBytes (mostly relevant for the client) to pair with ReadMaxBytes would be nice and prevent sending anything over the wire.

In our case, we configure ReadMaxBytes on the server, and would like to pair this also on our client so if a user attempts to send a message that is too large (and would ultimately be rejected by the server anyways), we can bail early on the client before doing any extra work.

This coincides with the gRPC `MaxCallSendMsgSize` option.

**Comment by akshayjshah** [comment]
@pkwarren are you still interested in taking this on? Totally fine if not, but I don't want to keep Matt waiting too long.

**Comment by pkwarren** [comment]
> @pkwarren are you still interested in taking this on? Totally fine if not, but I don't want to keep Matt waiting too long.

I've got most of this wired up - should have an update soon.
