### ISSUE TITLE
505 error with bidirectional streaming

### ISSUE THREAD

**Issue by asdine** [bufbuild/connect-go#342]
**Describe the bug**

It seems that using the default http client with bidirectional streaming returns a 505 error.
I suppose this is expected and we are supposed to use an http2 client or something, but the documentation doesn't provide a complete example of using bidi streaming so it's easy to fall into this problem.
If this is not a bug, could you share what should be used instead?

**To Reproduce**

Implement a simple service with bidi streaming and use the `http.DefaultClient`, without the `WithGRPC` flag.

Run the server like this:

```go
func main() {
    greeter := &GreetServer{}
    mux := http.NewServeMux()
    path, handler := greetv1connect.NewGreetServiceHandler(greeter)
    mux.Handle(path, handler)
    http.ListenAndServe(
        "localhost:8080",
        // Use h2c so we can serve HTTP/2 without TLS.
        h2c.NewHandler(mux, &http2.Server{}),
    )
}
```

Run the client like this:

```go
func main() {
  client := greetv1connect.NewGreetServiceClient(
  http.DefaultClient,
    "http://localhost:8080",
  )
  stream := client.Foo(context.Background())
  err := stream.Send(...)
  // no error returned here
  if err != nil { panic(err) }

  // should we call CloseRequest() ?
  // if not, Receive hangs forever
  err = stream.CloseRequest()
  // no error returned here
  if err != nil { panic(err) }

  resp, err := stream.Receive()
  // 505 error here
   if err != nil { panic(err) }
  // panic: unknown: HTTP status 505 HTTP Version Not Supported
}
```

**Environment:**
- `connect-go` v0.3.0
- `go version`:  1.19

**Additional context**
Happy to provide additional context if needed.

**Comment by akshayjshah** [comment]
Your diagnosis is correct: to serve & call bidi streaming RPCs, you must use HTTP/2. With `net/http`, you have two choices for how to accomplish this:

1. Use TLS. This is the simplest option - `http.DefaultClient` supports HTTP/2 with TLS already, and you can change the server from `http.ListenAndServe` to `http.ListenAndServeTLS`.
2. Use `golang.org/x/net/http2` to configure HTTP/2 without TLS (usually called h2c). The Go team has [intentionally made this laborious](https://github.com/golang/go/issues/14141#issuecomment-242452103), but we've documented how to set up your server and client [here](https://connect.build/docs/go/deployment#h2c).

As part of #295, we may try to make the client side of setting up h2c less painful.

**Comment by akshayjshah** [comment]
@asdine We'll also amend the docs to make this a bit clearer. I think that should resolve this issue; please let us know if you have further difficulty!

**Comment by asdine** [comment]
@akshayjshah Thanks!
