### ISSUE TITLE
Road to v1.0 🥇 

### ISSUE THREAD

**Issue by akshayjshah** [bufbuild/connect-go#343]
This isn't a specific issue or proposal. Instead, it outlines the work we need to finish before we tag a stable release of `connect-go`. We're planning to complete all these items by early October at the latest, but I'm hopeful that we'll be able to finish a bit sooner.

1. ~~Ship #331. We expect Connect handlers to work nicely with `net/http` middleware, and this is the most important missing piece. I'm confident we'll be able to implement this without breaking existing APIs, but it's worth being sure.~~
2. Prototype #295. RPC clients commonly need some control over discovery, health checking, and load balancing, and we plan to ship all of that in a separate package that constructs HTTP clients. We don't need a stable release of that package (or even a public beta), but we do need to ensure that we can implement basic functionality without changing the way Connect clients are constructed.
3. Ship an interceptor with more complex streaming functionality. Despite one round of breaking changes, I'm not 100% sure that the streaming interceptor interfaces are quite right; I'd like to implement an OpenCensus or OpenTelemetry interceptor to gain more confidence. We're planning to open source that interceptor in a separate package.
4. Solicit more feedback on the Connect protocol. Shipping a stable version of `connect-go` not only commits us to this package's APIs, it also commits us to keeping the Connect protocol backward-compatible. Buf's own [Studio](https://studio.buf.build) product uses the protocol, as do a few early adopters. We'll plan to check in with them, but otherwise there's nothing concrete to do here.

We'll plan to keep this issue updated as we make progress. Hopefully we'll tag a 1.0 earlier than planned! 🤞🏽

**Comment by akshayjshah** [comment]
For item 3 (a more complex streaming interceptor), we're planning to implement #344.

**Comment by tsingson** [comment]
great!
we use buf and connect in product for product ( half of grpc ) , it's work stable.
waiting for stream interceptor and load balance to replace all old grpc.

and, thanks Buf.Build team, great job.
wait for price plan.

**Comment by akshayjshah** [comment]
#331 is complete. One down, three to go! Next up is #344.

**Comment by akshayjshah** [comment]
We've done enough work on OTel, load balancing, and the protocol to be comfortable with a 1.0. Closing this and cutting a v1 now!
