### ISSUE TITLE
Support for OpenTelemetry interceptors

### ISSUE THREAD

**Issue by alehechka** [bufbuild/connect-go#344]
**Describe the solution you'd like**
To support capturing tracing data, it would be amazing to add out-of-the-box support for the OpenTelemetry standard into the `connect-go` client/server. This would likely be in the form of an interceptor function that can be optionally added to a server or client instance, similar to what is made available in [opentelemetry-go-contrib](https://github.com/open-telemetry/opentelemetry-go-contrib). That library does provide instrumentation for other well-known packages, so it could be possible to instead add a new instrumentation for `connect-go` inside their library.

**Describe alternatives you've considered**
Within my own playground for `connect-go` and `connect-web` I have been able to create a custom solution that uses the [net/http](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/net/http) instrumentation on the server-side, and a custom client-side interceptor to attach some relevant tracing data and the parent traceID to context.

My custom solution does work when using both the grpc-client and connect-go client to make requests, the resulting traces show the parent from the client and the child spans within the server.

With a better defined standard offered either in this library or as an instrumentation in [opentelemetry-go-contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) would allow other developers to easily add support for OpenTelemetry with out-of-the-box tracing attributes with their `connect-go` server/client instances.

**Comment by akshayjshah** [comment]
Hey @alehechka - good news! Internally, we're planning to migrate from OpenCensus to OpenTelemetry. We need standardized OTel interceptors for Connect anyways, so we're going to open-source them as a separate module. We're planning to ship these interceptors as part of #343, which we hope to wrap up by early October at the latest.

**Comment by akshayjshah** [comment]
I'm now actively working on this.

**Comment by nomad-software** [comment]
@akshayjshah Hi, are there any more updates for this yet? Thanks.

**Comment by akshayjshah** [comment]
I'm perpetually pulled into other work 😢 This issue is clearly important, though, so I'm handing it off to @joshcarp to make more rapid progress.

**Comment by nomad-software** [comment]
@akshayjshah @joshcarp Hi, are there any more updates for this yet? Thanks.

**Comment by joshcarp** [comment]
Hey @nomad-software 
Still WIP and hasn't been abandoned

**Comment by nomad-software** [comment]
Thanks @joshcarp for the update. Do you have an ETA for this please? I think it was pencilled in for the connect v1 release but has slipped since.

**Comment by joshcarp** [comment]
hey @nomad-software 
The [bufbuild/connect-opentelemetry-go](https://github.com/bufbuild/connect-opentelemetry-go) has been made public although it is unstable (so is opentelemetry I guess). 
There's still active development on it as it doesn't support streaming handlers/clients for tracing.

**Comment by nomad-software** [comment]
@joshcarp That's awesome, thanks a lot! :+1:

**Comment by akshayjshah** [comment]
We'll be tagging a release of bufbuild/connect-opentelemetry-go in a few days, so I'm going to close this issue. Sorry for the many, many delays everyone!

**Comment by akshayjshah** [comment]
And, as a final update: https://buf.build/blog/connect-opentelemetry-go/
