### ISSUE TITLE
Don't reuse messages between Receive() calls

### ISSUE THREAD

**Issue by mattrobenolt** [bufbuild/connect-go#345]
Disclosure: I'm not sure how well this pattern is reflected across the board for all streaming APIs, but I'm assuming it behaves similarly.

When using a service such as:

```proto
service Foo {
  rpc Bar(BarRequest) returns (stream BarResponse){}
}
```

Within the client streaming decoder, the same object is received _into_ for each iteration.

Specifically in a loop such as:

```go
for stream.Receive() {
  msg := stream.Msg()
}
```

`stream.Msg()` is the exact same object in memory. In most cases that use `proto.Unmarshal(...)`, it seems to be safe, though I'm not 100% sure.

If you happen to use a different codec, it's possible that the codec might not expect this to be an already potentially populated object.

While I don't think this is directly an issue with connect-go, since it appears the built in codec works fine `proto.Unmarshal(...)` seems to handle this case sufficiently, it's not a bug perse.

For contrast though, this behavior is distinctly different in grpc-go, so if there's code that's intended to interop, it might catch folks offguard (like it did for us).

In grpc-go, within `stream.Recv()`, it distinctly allocates a new struct for each call.

What I'd propose here though for connect-go is changing the behavior of `stream.Receive()` to allocate a new struct each time to avoid any issues. It's a slight regression in performance due to an extra allocation, but safely I think is preferable for the out of the box behavior.

Similarly though, I'd propose introducing a `ReceiveMsg(m any)` API that took a pointer, so I, as the caller, can control this behavior. Personally, in my case, I'd allocate one message first, then on each iteration, call `m.Reset()` or something similar to control this myself.

I think splitting `stream.Receive()` from a `stream.ReceiveMsg(m any)` makes sense from a UX POV too. I'd expect since the implementation details of `Receive()` are hidden, I'd expect more that this is 100% safe and I shouldn't be concerned with what it's doing. Whereas when `ReceiveMsg(m any)` takes the struct to inflate, I'd expect to be in control and make sure the struct is safe for re-use on each cycle.

This explicit split too allows a bit more control of any memory management if I were to want to leverage a memory pool (`sync.Pool`) or something similar for heavy workloads. Neither API currently allows that, whereas with grpc-go, we could.

I put together a concrete example to show off the differences: https://github.com/mattrobenolt/connect-go-example

The output of running this is as follows:

```bash
$ go run main.go
connect: Got greeting 0xc0001a4400: []string{"greeting 1"}
connect: Got greeting 0xc0001a4400: []string{"greeting 1", "greeting 2"}
grpc-go: Got greeting 0xc000042e40: []string{"greeting 1"}
grpc-go: Got greeting 0xc000352540: []string{"greeting 2"}
```

In grpc-go, you can see that it allocates a new struct within it's generated code: https://github.com/mattrobenolt/connect-go-example/blob/main/gen/greet/v1/greet_grpc.pb.go#L60-L67

I didn't test, but I assume within: https://github.com/bufbuild/connect-go/blob/main/client_stream.go#L91-L97

but I'm not actually sure how to mirror this behavior with generics. Since we don't know the concrete type of `Res`, we can't `new(Res)` or assign it to nil, etc. So it might require a slightly more complex fix, unfortunately. Maybe `s.msg = *(new(Res))` or similar?

Update:

Patching `s.msg = *(new(Res))` seems to be the closest immediate fix? It ends up, obviously reusing the same pointer, since it's the same chunk of memory, but it is filled with a new empty struct overwriting it. This might be the result you're going for.

My change:

```diff
diff --git a/client_stream.go b/client_stream.go
index 49cbea1..c0a9c3e 100644
--- a/client_stream.go
+++ b/client_stream.go
@@ -92,6 +92,7 @@ func (s *ServerStreamForClient[Res]) Receive() bool {
 	if s.constructErr != nil || s.receiveErr != nil {
 		return false
 	}
+	s.msg = *(new(Res))
 	s.receiveErr = s.conn.Receive(&s.msg)
 	return s.receiveErr == nil
 }
```

And my new test case output:
```
$ go run main.go
connect: Got greeting 0xc0001a4470: []string{"greeting 1"}
connect: Got greeting 0xc0001a4470: []string{"greeting 2"}
grpc-go: Got greeting 0xc0002d2300: []string{"greeting 1"}
grpc-go: Got greeting 0xc0003b22c0: []string{"greeting 2"}
```

So as we can see, it's the same memory address, but doesn't exhibit the same issue since the new object allocated is zero'd out.

Update 2:

ok, tbh this seems _better_, but I can't fully grasp the consequences of this, but it makes more logical sense to me.

```go
diff --git a/client_stream.go b/client_stream.go
index 49cbea1..89ec09f 100644
--- a/client_stream.go
+++ b/client_stream.go
@@ -76,7 +76,7 @@ func (c *ClientStreamForClient[Req, Res]) CloseAndReceive() (*Response[Res], err
 // exported constructor function.
 type ServerStreamForClient[Res any] struct {
 	conn StreamingClientConn
-	msg  Res
+	msg  *Res
 	// Error from client construction. If non-nil, return for all calls.
 	constructErr error
 	// Error from conn.Receive().
@@ -92,7 +92,8 @@ func (s *ServerStreamForClient[Res]) Receive() bool {
 	if s.constructErr != nil || s.receiveErr != nil {
 		return false
 	}
-	s.receiveErr = s.conn.Receive(&s.msg)
+	s.msg = new(Res)
+	s.receiveErr = s.conn.Receive(s.msg)
 	return s.receiveErr == nil
 }
 
@@ -100,7 +101,7 @@ func (s *ServerStreamForClient[Res]) Receive() bool {
 // returned message points to data that will be overwritten by the next call to
 // Receive.
 func (s *ServerStreamForClient[Res]) Msg() *Res {
-	return &s.msg
+	return s.msg
 }
 
 // Err returns the first non-EOF error that was encountered by Receive.
```

And now we, more as I'd expect, get a new memory address for each `Receive() + Msg()` combo.

**Comment by akshayjshah** [comment]
Huh, I didn't realize that vtprotobuf behaved this way. Thank you for filing such a detailed issue!

I'll open a PR to allocate a new struct on each call to `Receive` - it's an easy enough change, and I'd rather keep complexity out of codecs. We could do this without the complex `new` invocation you propose by leveraging zero values:

```go
var zero Res
s.msg = zero
```

As you point out, this fixes the bug but leaves the pointers returned by `Msg` all pointing at the same memory. This is a small performance win, but I think it opens us up to misuse down the road. It's less error-prone to go all the way to the final code snippet you have, where we allocate a new protobuf message on the heap for each call to `Receive`. Uncontroversial so far!

In the context of this codebase, I don't think it's a good idea to expose `ReceiveMsg`. Either the user now can't use `Msg`, or the stream struct needs to retain a reference to the passed-in pointer (gross and potentially buggy in the presence of pools). I just don't think that idiom coexists nicely with the iterator-style API connect has today, and I don't think the performance win is worth sacrificing the nicer iterator pattern. However, `ClientStream` and `ServerStreamForClient` are _very_ thin wrappers around `StreamingClientConn` and `StreamingHandlerConn`.  I think it's very reasonable to expose a method to expose the underlying conn, which you can wrap in a generic bring-your-own-pointer type pretty easily.

**Comment by timostamm** [comment]
vtprotobuf probably follows the typical protobuf semantics, where deserializing a message merges existing fields (singular fields are overwritten, repeated fields are concatenated, message fields are merged).

The default behavior of [proto.Unmarshal](https://pkg.go.dev/google.golang.org/protobuf/proto#UnmarshalOptions) and [protojson.Unmarshal](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#UnmarshalOptions.Unmarshal) on the other hand is to reset the message first. IMO this is desirable because in my experience, most users are unfamiliar with the merge semantics and the merge behavior catches them by surprise.

Ah, I see that vtprotobuf calls this out in the [readme](https://github.com/planetscale/vtprotobuf#available-features):

> To ensure proper `Unmarshal` semantics, ensure you've called `proto.Reset` on your message before calling `UnmarshalVT`, or that your message has been newly allocated.

Perhaps giving `connect-go` a vtprotobuf codec that uses `proto.Reset` before unmarshalling is also an alternative?

**Comment by akshayjshah** [comment]
> Perhaps giving connect-go a vtprotobuf codec that uses proto.Reset before unmarshalling is also an alternative?

We could, but I expect this to bite other `Codec` implementations too. I also expect that the current behavior will end up surprising people if they retain references to `stream.Msg()` and then call `Receive()` again. On balance, I think it's better to make this API harder to misuse; as a happy side effect, that makes a `vtprotobuf` codec a bit simpler too. The `vtprotobuf` repo has instructions for integration with `grpc-go` and Twirp; once this project has a stable release, I'll open a PR to add connect integration instructions too.
