### ISSUE TITLE
http.Request.{Proto,ProtoMajor,ProtoMinor} not set correctly for gRPC requests

### ISSUE THREAD

**Issue by chriso** [bufbuild/connect-go#367]
**Describe the bug**

The `http.Request.Proto*` fields appear to be set incorrectly for HTTP/2 requests. The `{Proto,ProtoMajor,ProtoMinor}` fields appear to always be set to `{"HTTP/1.1", 1, 1}`, regardless of whether connect is configured to use gRPC or connect-web.

We have something like the following:

```go
http1Transport := &http.Transport{...}
http2Transport := &http2.Transport{...}
transport := interceptor{http1Transport, http2Transport}
httpClient := &http.Client{Transport: transport}

connect.NewClient(httpClient, url, connect.WithGRPC())
```

We want to intercept HTTP requests and pass them off to the correct transport based on the value of the `req.ProtoMajor` inside the interceptor's `RoundTrip(req *http.Request)` implementation. The `transport` is used elsewhere where we make HTTP/1.1 requests, and we'd like to reuse the interceptor for both HTTP/1.1 and HTTP/2 requests. Unfortunately, `req.ProtoMajor` on requests originating from the connect client is always 1, so we're unable to route requests correctly.

Digging in to the code, it looks like the `duplexHTTPCall` helper creates a new `*http.Request` using `http.NewRequestWithContext`:

https://github.com/bufbuild/connect-go/blob/062122ca56ef77e244f50375db17837dab748dfc/duplex_http_call.go#L60-L65

The std lib `http.NewRequestWithContext` helper sets the `req.Proto*` fields to `{"HTTP/1.1", 1, 1}`: https://github.com/golang/go/blob/4a4127bccc826ebb6079af3252bc6bfeaec187c4/src/net/http/request.go#L888-L890

If I update `protocol_grpc.go` to set the fields to `{"HTTP/2", 2, 0}`, my code works as expected:

```go
diff --git i/protocol_grpc.go w/protocol_grpc.go
index 8d3fce0..a7030c0 100644
--- i/protocol_grpc.go
+++ w/protocol_grpc.go
@@ -251,6 +251,10 @@ func (g *grpcClient) NewConn(
        spec,
        header,
    )
+   duplexCall.request.Proto = "HTTP/2"
+   duplexCall.request.ProtoMajor = 2
+   duplexCall.request.ProtoMinor = 0
+
    conn := &grpcClientConn{
        spec:             spec,
        peer:             g.Peer(),
```

I can submit a PR, but you might have a better way to tackle the issue, or might have context/information I'm missing.

**Environment (please complete the following information):**
```
$ go version
go version go1.19.1 darwin/arm64
$ grep connect go.mod 
	github.com/bufbuild/connect-go v0.4.0
```

**Comment by akshayjshah** [comment]
Hey @chriso! Timo's correct - these fields of the `http.Request` aren't for client use, and they're ignored by `http.Client` and `http.Transport`. I'd prefer not to break that precedent, so these fields just aren't included our API contract.

Even if they were, the current values are correct. Like most HTTP clients, the standard library uses [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation) to upgrade to HTTP/2 where possible. Before connecting to the server, then, HTTP/1.1 is indeed correct. (gRPC servers support ALPN, so this should all work out of the box.)

Finally, there's no guarantee that we'll end up negotiating up to HTTP/2. There's a proposal in review to add a gRPC-over-HTTP/3 specification, and grpc-dotnet already ships with HTTP/3 support. I'd like `connect-go` to support HTTP/3 as soon as https://github.com/lucas-clemente/quic-go/issues/2266 is resolved.

If you need this behavior for your application, I suggest that you have your `http.RoundTripper` implementation look at the request's Content-Type and decide what to do from there.

**Comment by chriso** [comment]
Thanks for the quick response. I didn't realize the fields were ignored by the standard library, and TIL about [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation). We'll take a different approach in our code.
