### ISSUE TITLE
Distinguish between "the server ended the stream" and "the connection dropped unexpectedly"

### ISSUE THREAD

**Issue by haines** [bufbuild/connect-go#397]
**Is your feature request related to a problem? Please describe.**

We're using the connect protocol to stream messages from a server to a client. I seem to have misconfigured the reverse proxy in between them, so the connection drops after 30 seconds.

What surprised me, though, was that in this case `(*ServerStreamForClient).Err()` returns nil, even though the client never received the end-of-stream message.

It seems like when the connection dropped unexpectedly, the client receives an `io.EOF`, which is [suppressed](https://github.com/bufbuild/connect-go/blob/40a2428cb2609dd1ad02d1faaeafe87767887c15/client_stream.go#L132).

If the server closed the stream and the client received the end-of-stream message, then the error is `errSpecialEnvelope`, which is also suppressed since it wraps `io.EOF`.

It seems like it's not possible to distinguish between "the server ended the stream" and "the connection dropped unexpectedly".

**Describe the solution you'd like**

I would like `(*ServerStreamForClient).Err()` to only return nil if the client received the end-of-stream message from the server. If the client received `io.EOF` before receiving the end-of-stream message, then I would like it to return the error.

**Comment by akshayjshah** [comment]
Great point, @haines! We'll take a look and see how we can fix this.

**Comment by emcfarlane** [comment]
@haines client streams will now error with `io.ErrUnexpectedEOF` on dropped connections.
