### ISSUE TITLE
Error: no Grpc-Status trailer for wrapped http.ResponseWriters 

### ISSUE THREAD

**Issue by davidmdm** [bufbuild/connect-go#399]
**Describe the bug**

When making gRPC client requests to Connect-Server, if the http.ResponseWriter has been wrapped the resulting client call always fails with:

```
unknown: internal: gRPC protocol error: no Grpc-Status trailer
```

This makes certain common http middlewares that wrap the response writer incompatible with Connect-Go gRPC. 

**To Reproduce**

To make a minimal reproduction, I created a server using the Greet service from the getting started docs.

The only alteration to the server is wrapping the http.ResponseWriter with a noop wrapper:

```go
type RWWrapper struct {
	http.ResponseWriter
}

func WrapperMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.ServeHTTP(RWWrapper{w}, r)
	})
}

// ...

path, handler := greetv1connect.NewGreetServiceHandler(greeter)
mux.Handle(path, WrapperMiddleware(handler))
```

The example repository can be found here: https://github.com/davidmdm/connect-playground

The server command can be run with `go run ./cmd/server`
The client command can be run with `go run ./cmd/client`

The client command will result in the above error. 

**Environment (please complete the following information):**
- `connect-go`: v1.1.0
- `go version` : v1.19.3

- your complete `go.mod`:

```go
module github.com/davidmdm/connect-playground

go 1.19

require (
	github.com/bufbuild/connect-go v1.1.0
	golang.org/x/net v0.2.0
	google.golang.org/protobuf v1.28.1
)

require golang.org/x/text v0.4.0 // indirect

```

**Comment by mattrobenolt** [comment]
I'm speculating without investigating a ton, but http.ResponseWriter isn't fully enough to be compliant, it also needs to implement http.Flusher.

This is definitely a wart about the stdlib net/http module, but it is what it is.

connect-go (any other implementation) need to explicitly test against this interface: https://github.com/bufbuild/connect-go/blob/main/protocol.go#L300-L304

And this is documented in net/http docs: https://pkg.go.dev/net/http#Flusher

> The default HTTP/1.x and HTTP/2 ResponseWriter implementations support Flusher, but ResponseWriter wrappers may not. Handlers should always test for this ability at runtime.

I would suggest doing something like this: https://go.dev/play/p/geC2Ns2zotI

```go
type RWWrapper struct {
	http.ResponseWriter
}

func (w *RWWrapper) Flush() {
	if f, ok := w.ResponseWriter.(http.Flusher); ok {
		f.Flush()
	}
}

// assure our wrapper satisfies both http.ResponseWriter and http.Flusher
var (
	_ http.ResponseWriter = (*RWWrapper)(nil)
	_ http.Flusher        = (*RWWrapper)(nil)
)
```

**Comment by davidmdm** [comment]
You are correct. Closing issue. Thanks for finding this for me. I was losing my mind!

**Comment by mattrobenolt** [comment]
Playing around a tad more since I was curious, this might be a decent option:

```go
type responseWriterFlusher interface {
	http.ResponseWriter
	http.Flusher
}

type RWWrapper struct {
	responseWriterFlusher
}

// assure our wrapper satisfies both http.ResponseWriter and http.Flusher
var _ responseWriterFlusher = (*RWWrapper)(nil)

func main() {
	mux := http.NewServeMux()
	mux.Handle("/", WrapperMiddleware(http.NewServeMux()))

}

func WrapperMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if rwf, ok := w.(responseWriterFlusher); ok {
			h.ServeHTTP(&RWWrapper{rwf}, r)
		} else {
			// we simply require both interfaces to be satisfied, so there's nothing
			// more reasonable we can do, and your server is implemented incorrectly.
			panic("uh oh")
		}

	})
}
```

**Comment by davidmdm** [comment]
This is a very elegant solution! Thanks 😄
