### ISSUE TITLE
Add handler to AnyRequest

### ISSUE THREAD

**Issue by lordnynex** [bufbuild/connect-go#400]
**Is your feature request related to a problem? Please describe.**

I tend to create services that serve multiple RPC services. The endpoints within the service are mixed public/private. For example

```protobuf
service UserService {
  Login(LoginRequest) returns (LoginResponse); // Public 
  GetAccount(GetAccountRequest) returns (GetAccountResponse); // Private
}
```

As a consequence, I historically use [grpc ecosystem's auth middleware](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/auth), and my service handlers satisfy the [ServiceAuthFuncOverride interface](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/auth/auth.go#L30). 

When setting out to port this interceptor to connect, I hit a dead end because I can not perform the [ServiceAuthFuncOverride interface assertions](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/99612e884e71d96a3c8dd30ad4d8eccacfa91798/auth/auth.go#L39) on the handler. This is because [AnyRequest](https://pkg.go.dev/github.com/bufbuild/connect-go#AnyRequest) does not have a reference to the matched handler. 

**Describe the solution you'd like**

A mechanism to access the handler from `AnyRequest`, or (probably breaks the API) pass the handler to [UnaryFunc](https://pkg.go.dev/github.com/bufbuild/connect-go#UnaryFunc).

**Describe alternatives you've considered**

I suppose an alternate lookup method is possible, but seems sub-optimal. 

**Additional context**

I intend to do access control in this way within the service itself. This is also an ideal place for me to add policy information to `context.Context` that is later utilized in my database access layer.

**Comment by akshayjshah** [comment]
We discussed this in Slack, but for posterity:

Luckily, `connect-go` doesn't need this degree of indirection. Something similar to the following should work:

```go
type AuthFunc func(context.Context, connect.AnyRequest) (context.Context, error)

func WithAuthentication(f AuthFunc) connect.HandlerOption {
  return connect.WithInterceptors(&myAuthInterceptor{f})
}

// You'll have to implement connect.Interceptor.
type myAuthInterceptor {
  f AuthFunc
}
```

Then, you can construct your handlers like this:

```go
impl := &myFooImplementation{}
// If *myFooImplementation has an Authenticate method that matches AuthFunc
h := foov1connect.NewFooHandler(impl, WithAuthentication(impl.Authenticate))
// Or you can use a global AuthFunc
h = foov1connect.NewFooHandler(impl, WithAuthentication(globalAuthFunc))
```

Ping us here or in Slack if you feel like open-sourcing your implementation :)
