### ISSUE TITLE
Allow custom User-Agent

### ISSUE THREAD

**Issue by jacobwgillespie** [bufbuild/connect-go#401]
It would be awesome to allow overriding the `User-Agent` header - before adopting connect-go, my application was sending a custom `User-Agent` to the server, with information about the client and version. Currently it appears that connect-go always uses its own `User-Agent` value.

**Describe the solution you'd like**
connect-go could only send its own `User-Agent` if another had not already been set.

**Describe alternatives you've considered**
For now, we'll be using another metadata value, but would prefer to use `User-Agent`.

**Comment by akshayjshah** [comment]
Sending another User-Agent seems reasonable! Are you trying to send a different `User-Agent` for each request, or are you trying to set a custom User-Agent for all requests? The second case seems like it'll be much more common, and you can do it today with a small interceptor:

```go
func WithUserAgent(agent string) connect.ClientOption {
  return connect.WithInterceptors(&agentInterceptor{agent})
}

type agentInterceptor struct {
  agent string
}

func (i *agentInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
  return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
    req.Header().Set("User-Agent", i.agent)
    return next(ctx, req)
  }
}

func (i *agentInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
  return func(ctx context.Context, spec connect.Spec) connect.StreamingClientConn {
    conn :=  next(ctx, spec)
    conn.RequestHeader().Set("User-Agent", i.agent)
    return conn
  }
}

func (i *agentInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
  return next
}
```
