### ISSUE TITLE
Testing strategy with error codes

### ISSUE THREAD

**Issue by dghubble** [bufbuild/connect-go#402]
**Is your feature request related to a problem? Please describe.**

Writing tests for a simple connect server that implements a service like:

```proto
service ExampleAPI {
  rpc GetExample(GetExampleRequest) returns (Example) {}
}
```

Writing a table-driven test that checks errors, we might write

```go
cases := []struct {
  name         string
  ...
  expectedErr  error
}{
  {"some-id", nil},
  {"missing-id", connect.NewError(connect.CodeNotFound, nil)}
}

for _, c := range cases {
  resp, err := server.GetExample(ctx, connect.NewRequest(...))
  assert.Equal(t, connect.CodeOf(c.expectedErr), connect.CodeOf(err))
}
```

The awkwardness of this approach is having to build a fake error with `connect.NewError(connect.CodeNotFound, nil)`, so that we can later unpack the code and compare it against the actual error.

Another table-driven approach we might write just checks codes,

```go
cases := []struct {
  name         string
  ...
  expectedCode connect.Code
}{
  {"some-id", 0},
  {"missing-id", connect.CodeNotFound)}
}

for _, c := range cases {
  resp, err := server.GetExample(ctx, connect.NewRequest(...))
  assert.Equal(t, c.expectedCode, connect.CodeOf(err))        // won't work
}
```

The awkwardness of this approach is that there is no `connect.CodeOK`. You might just put your own 0 value there, but `connect.CodeOf(nil)` gives an unknown code (not surprising).

Package designers, what conventions would you like people to take when testing with this package?

* Should we compare `error`'s or codes? Error's might be more aligned with HTTP testing
* Should there be a `CodeOK`?
* When a handler errors (e.g. can't get an `Example`), should it return a `connect.NewResponse(nil)` or a `nil`

**Additional context**

Taking a look at [connect-demo](https://github.com/bufbuild/connect-demo) it doesn't really ever test error codes or do table driven tests like you might do in a larger application.

I love the change you folks are trying to make in this space btw!

**Comment by akshayjshah** [comment]
Great questions, @dghubble!

> Should we compare error's or codes? Error's might be more aligned with HTTP testing

Connect errors are much richer than the standard library's `error` interface: they include a code, metadata, and error details too. How you compare them depends on (a) how picky you'd like to be, and (b) your assertion library of choice (if any). For your particular need, I think something like this should work pretty well:

```go
func ptr[T any](val T) *T {
  return &val
}

cases := []struct {
  name         string
  ...
  expectedCode *connect.Code
}{
  {"some-id", nil},
  {"missing-id", ptr(connect.CodeNotFound)}
}

for _, c := range cases {
  resp, err := server.GetExample(ctx, connect.NewRequest(...))
  if c.expectedCode == nil {
    assert.Nil(t, err)
  } else {
    assert.Equal(t, connect.CodeOf(err), c.expectedCode)
  }
}
```

If you want a more thorough assertion, the best approach right now is to implement your own `cmp.Transformer` function. You'll need to make some decisions if you do this:

* Do you care about the types of the underlying errors, or just their string representations?
* Do you care about the casing of HTTP header/trailer keys?
* Do you care about the ordering of error details?
* Do you care whether error details have the same wire representation, or just that they represent semantically-equivalent protobuf messages?

Eventually, I'd like to offer a `cmp`-specific package of helpers that makes some of this easier.

> Should there be a CodeOK?

Early revisions of `connect-go` had `CodeOK`, and I found it quite awkward.

What should `NewError(CodeOK, fmt.Errorf("fail"))` return? We have to assume that the caller made a mistake: either the code is a mistake and we replace it with `CodeUnknown`, or the underlying error is a mistake and we return `nil`. The latter matches `grpc-go` more closely, but returning a typed nil is _very_ error-prone. Decisions here end up infecting a variety of other APIs, too.

The current approach isn't perfect, but it has the benefit of simplicity.

> When a handler errors (e.g. can't get an Example), should it return a connect.NewResponse(nil) or a nil

As long as it's also returning a non-nil error, it doesn't matter. The `connect-go` runtime follows the usual Go convention and assumes that a non-nil error indicates that any other returned values aren't safe to use. Returning `nil, connect.NewError(...)` is clearer and more efficient, so I'd lean toward that unless it makes the rest of the code much more awkward.

**Comment by dghubble** [comment]
Thanks for the detailed reply! I've been considering this further.

Overall, I like that server implementations can return an `error` that contains a code (like gRPC and unlike `net/http`) and additional details. And that we can take advantage of more recent developments like `errors.As` or `errors.Is`.

```go
# net/http - not an actual error type, just a write operation
http.Error(w, "some message", http.StatusNotFound)
```

```go
# connect-go
return nil, connect.NewError(connect.CodeNotFound, fmt.Errorf("some message"))
```

```go
# grpc
return nil, status.Errorf(codes.NotFound, "some message")
```

For now I only have cases that need to look at the status code of the error, the message usally varies (e.g. contains ids) so its less useful to compare on. Your approach of using the pointer to a Code or a nil works alright, though I might keep the first approach.

One convenience I was thinking about that might help is:

```go
connect.NewErrorf(c Code, format string, a ..any)
```

I think the reason `connect.NewError(connect.CodeNotFound, nil)` feels "odd" is that its jarring to create a NewError but set `err` to `nil`.  Whereas `connect.NewErrorf(connect.CodeNotFound, "")` reads like a new error where the message happens to be empty.

> Early revisions of connect-go had CodeOK, and I found it quite awkward.

Agreed, its felt awkward in gRPC too and `NewError(CodeOK, fmt.Errorf("fail"))` is jarring too. I think its a side effect of status codes now being specific to and embedded in error's (as opposed to HTTP where the status code is applicable for all responses). It just doesn't make sense to talk about a code for the good / non-error case in RPC. Thanks for sharing the backstory.
