### ISSUE TITLE
Handler returning nil response results in cryptic stack trace.

### ISSUE THREAD

**Issue by jchadwick-buf** [bufbuild/connect-go#405]
**Is your feature request related to a problem? Please describe.**
When a handler returns a `nil` response, it leads to a rather cryptic panic.

```go
func (*PingServer) Ping(
	context.Context,
	*connect.Request[pingv1.PingRequest],
) (*connect.Response[pingv1.PingResponse], error) {
	return nil, nil
}
```

```
2022/11/28 09:51:26 http: panic serving 127.0.0.1:59973: runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:1850 +0xb0
panic({0x104c23860, 0x104f1a660})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/panic.go:890 +0x258
github.com/bufbuild/connect-go.(*Response[...]).Header(0x4?)
        /Users/john/go/pkg/mod/github.com/bufbuild/connect-go@v1.1.0/connect.go:210 +0x18
github.com/bufbuild/connect-go.NewUnaryHandler[...].func2({0x12c76ca98, 0x1400014a3e0})
        /Users/john/go/pkg/mod/github.com/bufbuild/connect-go@v1.1.0/handler.go:72 +0x1b8
github.com/bufbuild/connect-go.(*Handler).ServeHTTP(0x14000108280, {0x104c969a8, 0x140001c68a0}, 0x140001ba300)
        /Users/john/go/pkg/mod/github.com/bufbuild/connect-go@v1.1.0/handler.go:213 +0x410
net/http.(*ServeMux).ServeHTTP(0x0?, {0x104c969a8, 0x140001c68a0}, 0x140001ba300)
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2487 +0x140
net/http.(*ServeMux).ServeHTTP(0x1400006d828?, {0x104c969a8, 0x140001c68a0}, 0x140001ba300)
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2487 +0x140
main.logger.func1({0x104c96bb8?, 0x140001be2a0}, 0x140001ba300)
        /Users/john/Code/basic-grpc-server/main.go:84 +0xa0
net/http.HandlerFunc.ServeHTTP(0xd0b880cd9aa8c9fb?, {0x104c96bb8?, 0x140001be2a0?}, 0x1047c596c?)
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2109 +0x38
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x104c94900?, 0x1400012a3f0?}, 0x14000158580?}, {0x104c96bb8, 0x140001be2a0}, 0x140001ba300)
        /Users/john/go/pkg/mod/golang.org/x/net@v0.1.0/http2/h2c/h2c.go:124 +0x408
net/http.serverHandler.ServeHTTP({0x104c95ab0?}, {0x104c96bb8, 0x140001be2a0}, 0x140001ba300)
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:2947 +0x2c4
net/http.(*conn).serve(0x14000139400, {0x104c97140, 0x1400011fb00})
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:1991 +0x560
created by net/http.(*Server).Serve
        /opt/homebrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:3102 +0x444
```

**Describe the solution you'd like**
It would be nice if there was some kind of detection for this scenario, so that it's easier to tell why it crashed. The stack trace doesn't really give any clues as to which handler crashed or why, so it could be quite insidious inside a larger project.

**Comment by akshayjshah** [comment]
Ugh, the `[...]` in `github.com/bufbuild/connect-go.NewUnaryHandler[...]` is throwing away exactly the information that we care about here.

I'm not sure what the best way to fix this is, especially server-side - the only way an `http.Handler` has to tell the server owner something without sending it to the client is to panic. Sending `CodeInternal: can't marshal nil *connect.Response[foopb.FooRequest]` to the client is graceful and explicit, but feels like it's leaking some internal details best kept private. Perhaps an explicit panic that includes the procedure name is the best option?

**Comment by jchadwick-buf** [comment]
I've been thinking about it a bit, and I think the most reasonable thing to do would be to do an explicit panic. It's a programmer error, and that's the action I think makes the most sense in that case. It'll at least be more helpful to know why the problem is occurring even if it can't pinpoint _where_ it happened.

**Comment by mfridman** [comment]
I was doing some other stuff on the weekend and ran into the same issue. I was a bit puzzled at first but quickly realized my error.

Agree this is a programmer error and +1 for the proposed solution:

> explicit panic that includes the procedure name is the best option.

Having a clear panic message with the procedure would have been enough to quickly identify the issue.

![CleanShot 2022-11-29 at 14 51 54@2x](https://user-images.githubusercontent.com/6278244/204634150-d3bacd92-5d3d-490b-bf90-1e26d5136792.png)
