### ISSUE TITLE
expose an API for constructing a wire error

### ISSUE THREAD

**Issue by jhump** [bufbuild/connect-go#420]
When using `connect.NewError`, it is not possible create an error such that `err.IsWireError()` will return true.

This capability is particularly useful for dealing with bidi streaming APIs that represent a conversation, where each response message correlates with a request message. It is common for these kinds of APIs to support partial success by having a response message indicate a failure just for that one request message. Often such APIs use `google.rpc.Status` in the response message to indicate a possible failure. Sometimes they [do not](https://github.com/grpc/grpc/blob/v1.49.2/src/proto/grpc/reflection/v1alpha/reflection.proto#L132-L136).

For this sort of use, it is commonplace for the calling Go code to translate that status into an error. Since the error was received over the wire during an RPC call, it should technically be a wire error, so that any other handling/propagation logic higher up the stack can react to it correctly.

This could be addressed as easily as introducing a new `NewWireError` function with the same signature and semantics as `NewError` except that the returned error will return true when `err.IsWireError()` is called.

**Comment by akshayjshah** [comment]
Huh, I'd never noticed that portion of the reflection API. TIL!

Happy to take a PR for this. I'm 50/50 on whether we ought to special-case `NewWireError` or anticipate more things down the road and add `NewErrorOpt(Code, error, ...ErrorOption)` (function name is terrible, but you get the idea).

**Comment by akshayjshah** [comment]
Here's another example of an API using a similar pattern: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#partial-success
