### ISSUE TITLE
Support Content-Type `text/plain`

### ISSUE THREAD

**Issue by lujiajing1126** [bufbuild/connect-go#429]
**Is your feature request related to a problem? Please describe.**

We are using `connect-go` in our data collector of an observability platform. The endpoint is designed for both mobiles (including iOS and Android) and browsers (PC and mobile phone).

We are using `gGPRC-web+proto` as our protocol.

![image](https://user-images.githubusercontent.com/2568208/209047969-16ea4bc3-f5c1-497d-8a95-3813c57656b3.png)

We've observed long preflight latency for the first request while loading a webpage.

![image](https://user-images.githubusercontent.com/2568208/209047611-39cedc39-3a34-4dc4-8fff-749b3a94570d.png)

Before that, a private protocol is used which converts protobuf binary to b64 encoded text data and sent to an endpoint with `Content-Type: text/plain`.  This could avoid any uncessary CORS validation according to the HTML5 Spec https://stackoverflow.com/questions/39498731/cors-why-there-arent-a-pre-flight-request-for-post-with-content-typetext-plai.

This is what exactly the [`Sentry`](https://github.com/getsentry/sentry-javascript) is using.

Both latency and message size (i.e. bandwidth) is critical in such performance profiling scenarios.

**Describe the solution you'd like**

We could add `text/plain` support for `application/grpc-web-text` protocol?

**Describe alternatives you've considered**

**Additional context**

**Comment by mattrobenolt** [comment]
Rather than adapting Connect for this, I personally think this would be better suited in a very thin HTTP middleware that rewrites the header for you from text/plain into whatever Connect expects. This seems rather niche case that is easily solved outside of the core library.

**Comment by akshayjshah** [comment]
Hi @lujiajing1126! CORS is defined as part of the [`fetch` specification](https://fetch.spec.whatwg.org) - it's definitely a bit of a pain in situations like this!

Unfortunately, we can't add `text/plain` support to the gRPC-Web protocol - the protocol is specified [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md), and it only allows content-types that begin with `application/grpc-web` or `application/grpc-web-text`. It also uses quite a few request headers (`grpc-timeout`, `grpc-accept-encoding`, etc.) that aren't part of the [CORS safelist](https://fetch.spec.whatwg.org/#cors-safelisted-request-header) - regardless of content-type, any requests with those headers must be preflighted.

As @mattrobenolt suggests, you can certainly write some `net/http` middleware that lets you base64-encode request bodies and use the `text/plain` content-type. (You'd need to write similar code in JS too, of course.) At this point, you're devising your own ad-hoc RPC protocol - compared to grpc-web with binary protobuf payloads, you'll increase message size but avoid CORS preflighting.

Before you do this, have you tried letting the browser cache preflight responses using [`Access-Control-Max-Age`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age)? You should only need one preflight request every 2h in Chrome and every 24h in Firefox. If necessary, you can make a dummy RPC on page load to ensure that the browser cache is full. [We do this in our small demo application](https://github.com/bufbuild/connect-demo/blob/main/main.go#L123), and it's been working well.

**Comment by lujiajing1126** [comment]
Thanks @mattrobenolt @akshayjshah for the suggestion.

> As @mattrobenolt suggests, you can certainly write some `net/http` middleware that lets you base64-encode request bodies and use the `text/plain` content-type. (You'd need to write similar code in JS too, of course.) At this point, you're devising your own ad-hoc RPC protocol - compared to grpc-web with binary protobuf payloads, you'll increase message size but avoid CORS preflighting.

I've rechecked the `grpc-web` spec and the `connect-go` implementation. The ad-hoc implementation is similar to the `grpc-web+text` protocol which is only an alternative for IE-10 and it has been abandoned in `connect-go`.

I will further check the possibility of a customized `net/http` middleware.

> Before you do this, have you tried letting the browser cache preflight responses using [`Access-Control-Max-Age`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age)? You should only need one preflight request every 2h in Chrome and every 24h in Firefox. If necessary, you can make a dummy RPC on page load to ensure that the browser cache is full. [We do this in our small demo application](https://github.com/bufbuild/connect-demo/blob/main/main.go#L123), and it's been working well.

Sure. We are using CORS with `connect-go` now as [demonstrated in the Demo Service](https://github.com/bufbuild/connect-demo/blob/main/main.go). But since we are providing mobile payment services, users may not open the web page very frequently, e.g. for breakfest, lunch and dinner. So 2hr cache policy may not be effective in our cases.

**Comment by akshayjshah** [comment]
Unfortunately, the content-type is part of the gRPC-Web specification. We're not planning for this implementation to diverge from the specification.

If you're setting Access-Control-Max-Age on your CORS preflight responses and that's still not sufficient, it seems like you can either:

* implement a `net/http` middleware to change the content-type and base64-decode the body, _or_
* on your webpage, make an RPC in the background _before_ the user begins a latency-sensitive operation. That should refresh the CORS cache.

**Comment by lujiajing1126** [comment]
Thanks. I will close this issue.
