### ISSUE TITLE
Interceptors can modify the headers in potentially dangerous ways

### ISSUE THREAD

**Issue by jhump** [bufbuild/connect-go#430]
There are a handful of headers that callers should never try to set:
1. `grpc-*`: These headers generally control aspects of the protocol. Those that aren't defined are reserved for future use. Changing these out from under the library could lead to corrupt/junk requests and responses.
2. `connect-*`: Same as above. Though the protocol spec for connect does not explicitly call out that all headers with this prefix are reserved for future use; it simply describes the ones that are part of the protocol as of now.
3. `accept`, `content-type`, `accept-encoding`, `content-encoding`, `te`: These are explicitly part of the protocols and should only be set by the library that implements the protocol.
4. `transfer-encoding`: Part of the on-the-wire representation for streaming bodies in HTTP 1.1. Disallowed in HTTP/2. Like above, this should only be set (if set at all) by the library that implements the protocol.

The Connect library does not complain if a client or server tries to use these. For many of these headers (but not all), they will be silently overwritten by the protocol implementation, which is probably the right way to go.

However, for maximum safety/predictability, the protocol implementations should sanitize (fix or strip) the above headers consistently for all requests. Furthermore, when the protocol implementations overwrite the user-provided headers, they do so _before_ application code is run. For unary and server-streaming RPCs, only interceptors can dangerously modify the headers. But for client- and bidi-streaming RPCs, application code can also modify/set headers that should be disallowed.

If the headers are created eagerly so that interceptors can _inspect_ them, that seems reasonable. But they need to then be sanitized before actually sending on the wire. I would argue, however, that is _not_ necessary for interceptors and application code to view protocol-specific headers, so it would be safer to move the step of setting protocol-specific headers to just before the headers are written. (For code that really cares about all of the actual on-the-wire headers, HTTP middleware could be used.)

**Comment by akshayjshah** [comment]
> Though the protocol spec for connect does not explicitly call out that all headers with this prefix are reserved for future use; it simply describes the ones that are part of the protocol as of now.

Reasonable to explicitly mention this - I'll amend the docs.

> However, for maximum safety/predictability, the protocol implementations should sanitize (fix or strip) the above headers consistently for all requests.

How big of a concern is this? I avoided doing this intentionally, because I've found `grpc-go`'s insistence on this inconvenient on many occasions (they didn't even support `grpc-accept-encoding` properly until Oct 2022). It seems to me that people are very unlikely to set these headers by mistake, and that we should allow users who know what they're doing to monkey around at will.

**Comment by jhump** [comment]
> users who know what they're doing to monkey around at will

Seems a little dangerous to modify headers that define the protocol out from under the implementation. At the same time, I don't feel too strongly that it needs to be enforced in code. So we can close this issue if you want, or maybe convert to a documentation issue.

I think it _should_ be made clear somewhere in the docs that headers explicitly referenced in the connect and grpc protocol descriptions should not be used by application code (in addition to reserving "connect-*" for future connect protocol use, as "grpc-*" is reserved for their future use). And it's probably useful to call this out somewhere _other_ than the protocol specification doc: it's useful for users of the library, too, who may not care about protocol details.

**Comment by akshayjshah** [comment]
All good suggestions. I've opened bufbuild/connect-docs#188 to update the protocol description, and I'll open a PR here to more prominently document safe header usage.

Agree that modifying headers out from under the application is a little dangerous, but it also seems unlikely to happen by accident. I don't mind sanitizing headers if this becomes a significant problem in practice, but I'd rather not be super-defensive about it from now.
