### ISSUE TITLE
pkg.go.dev example doesn't compile

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/connect-go#433]
**Describe the bug**

The example doesn't work here:
https://pkg.go.dev/github.com/bufbuild/connect-go#example-package-Handler

Fails with the error
```
Output:

go: downloading github.com/bufbuild/connect-go v1.4.1
go: downloading google.golang.org/protobuf v1.28.1
package play.ground
	prog.go:8:2: use of internal package github.com/bufbuild/connect-go/internal/gen/connect/ping/v1 not allowed
package play.ground
	prog.go:9:2: use of internal package github.com/bufbuild/connect-go/internal/gen/connect/ping/v1/pingv1connect not allowed
```
The solution here would be either
- Move protos from internal to something that isn't restrictive like `private`
- Create a BSR module and remove internal/gen completely
- Create another example in https://github.com/bufbuild/connect-go/blob/main/handler_example_test.go so that it is not rendered as a runnable example

From the docs [here](https://go.dev/blog/examples)

> To achieve this we can use a “whole file example.” A whole file example is a file that ends in _test.go and contains exactly one example function, no test or benchmark functions, and at least one other package-level declaration. When displaying such examples godoc will show the entire file.

**Comment by akshayjshah** [comment]
Agreed that having the examples not run on `pkg.go.dev` isn't ideal.

> Create another example in https://github.com/bufbuild/connect-go/blob/main/handler_example_test.go so that it is not rendered as a runnable example.

Something like this is the best of the available options. I'll open a PR to make this more like the client example. Unfortunately, it'll make it harder to see the service implementation, but perhaps that's okay.

> Move protos from internal to something that isn't restrictive like private

I'd rather be _very_ cautious about Connect's exported API. No matter what we name these packages, [Hyrum's Law](https://www.hyrumslaw.com/) applies and we'll inevitably end up with people upset when we make breaking changes to these internal-only schemas.

> Create a BSR module and remove internal/gen completely

This is appealing on some levels, but it makes changing the schemas _very_ annoying - you end up with a multi-step workflow that requires multiple PRs. Less concretely, it makes `connect-go` seem coupled to Buf and the BSR.

**Comment by joshcarp** [comment]
Thought that might work; if the generated code was generated into a test package then it could be run in pkg.go.dev but not be imported anywhere externally?

**Comment by akshayjshah** [comment]
Possible, but AFAIK there's no such thing as a "test package" - we'd need to generate, then rename all the files to end with `_test`. Seems like we're again getting problematically far from what users will actually be doing.

**Comment by joshcarp** [comment]
Further thinking about it I think that this is a bug in pkg.go.dev as the run button shouldn't even be there because it's a non runnable example; if it did run it would timeout the server anyway

**Comment by joshcarp** [comment]
Raised an issue on golang/go because imo this shouldn't be showing a run button: https://github.com/golang/go/issues/57703

**Comment by joshcarp** [comment]
Because this is an issue with pkgsite I feel like it might be worth closing this issue

**Comment by akshayjshah** [comment]
Agree.
