### ISSUE TITLE
It would be nice with get methods that checks for nil for Response fields

### ISSUE THREAD

**Issue by andersroos** [bufbuild/connect-go#443]
Code generated with protoc creates nice Get methods for fields so that you do not have to do nil checks when fetching fields in gRPC responses unless you want to.

I think such methods should exists on `connect.Response` too since the current API forces awkward nil checks in some situations.

I can make a PR if you think it is a good idea to add `GetMsg`, `GetAny`, `GetHeader`, and `GetTrailer` to `connect.Response`.

Alternatively `Any`, `Header` and `Trailer` could have the nil check added, but that would be an API breaking change so probably not a good idea.

**Comment by akshayjshah** [comment]
Hi @andersroos! Can you clarify why you're doing nil checks for these fields?

* `Response.Msg` is never nil. If it is, a panic is appropriate - there's a critical correctness problem, likely in an interceptor.
* `Response.Any()` is never nil - partly because `Msg` is never nil, but mostly because there's _always_ at least a type.
* `Response.Header()` is never nil.
* `Response.Trailer()` is never nil.

**Comment by andersroos** [comment]
Hello @akshayjshah!

To clarify: I mean the situation when `Response` is nil (which is is when there is an error), not when the individual fields are nil.

When you use plain gRPC with proto payloads the generated objects have access methods which makes nil checks. This can we very convenient sometimes. For example when you have a helper method that does both error checking and uses a sub part of the message. Then you don't have to do error checking before calling the helper, for example like this using regular gRPC:
```
response, err := client.Method(ctx, &service.SomeRequest{})
// This is not possible with connect because you have to check if response is nil before accessing response.Msg
return helper(response.GetSomePart().GetSomSubPart(), err) 
```

**Comment by akshayjshah** [comment]
I see. In this case, I think we're going to stick with standard Go semantics - if a function returns a non-nil error, users should assume that the other returned values aren't safe to use.

If you'd prefer something more like what you're proposing, you can do so with a small helper function:

```go
func OrZero[T any](req *connect.Request[T]) *connect.Request[T] {
	if req != nil {
		return req
	}
	var zero T
	return connect.NewRequest(&zero)
}
```
