### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mehdipourfar** [bufbuild/connect-go#450]
I have a python grpc server and I want to use connect-web for my frontend. Is there anyway to use this package as a proxy for non-golang grpc servers?

**Comment by joshcarp** [comment]
Hey @mehdipourfar, 
Unfortunately that functionality is not provided by connect-go. This library itself is more concerned with providing connect support for go specifically. 

The behavior you're describing, however, will be provided soon by https://github.com/envoyproxy/envoy and there is an open PR up https://github.com/envoyproxy/envoy/pull/24836 that will add a bridge between grpc <-> Connect. In this case your backend will be able to continue using gRPC and envoy will be able to convert to Connect and vise versa, allowing you to use connect-web on the frontend.

**Comment by akshayjshah** [comment]
Adding to @joshcarp's response: you _could_ build a proxy using this package, but it would be quite a bit of work.

You're much better off starting with `connect-web` [configured to use the gRPC-Web protocol](https://connect.build/docs/web/choosing-a-protocol#grpc-web). Run Envoy as a proxy for your Python backend with the gRPC-Web filter enabled (here's an [example configuration](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml)). Your `grpc-python` server can remain unchanged. You won't get all the benefits of the Connect _protocol_, but you'll still be able to use `protobuf-es` and `connect-web` in the browser.

When https://github.com/envoyproxy/envoy/pull/24836 is released, upgrade your Envoy proxy to the new version. With the same configuration, it will be able to translate from the Connect RPC protocol to standard gRPC (just as it does for gRPC-Web today). At that point, you can switch your `connect-web` code to [use the Connect RPC protocol](https://connect.build/docs/web/choosing-a-protocol/#connect). None of your application code will need to change, and you'll get all the debugging and ease-of-use benefits of the new protocol.

I'm going to close this issue - feel free to ping this issue or reach out to us in [Slack](https://https://buf.build/links/slack) if you have further questions!

**Comment by mehdipourfar** [comment]
Thanks for your information. It seems that your pull request has been merged. I'm using latest version of [envoy-dev](https://hub.docker.com/r/envoyproxy/envoy-dev/tags).
It seems to work for gprc-web. Since I'm not a frontend engineer, I'm using [sonara](https://github.com/public/sonora) as client for testing envoy proxy and it works fine.
But how can I test the connect protocol of envoy? I've tried to test it with a curl command like this which is burrowed from your README file:
```
curl \
    --header "Content-Type: application/json" \
    --data '{"sentence": "I feel happy."}' \
    https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Say
```
But envoy returns service unavailable status for requests that don't have `Content-Type: application/grpc-web-text` header.

**Comment by akshayjshah** [comment]
@mehdipourfar You'll also need `--header "Connect-Protocol-Version: 1"`. All the generated clients (`connect-go`, `-web`, `-swift`, and the upcoming `-node` and `-kotlin`) add this header automatically.

@jchadwick-buf can help if you have any trouble configuring Envoy properly.
