### ISSUE TITLE
Unexpected errors on empty HTTP request bodies

### ISSUE THREAD

**Issue by torkelrogstad** [bufbuild/connect-go#452]
When doing a HTTP request without a body I end up with this response: 

```json
{"code":"invalid_argument","message":"unmarshal into *emptypb.Empty: proto: syntax error (line 1:1): unexpected token "}   
```

This is fixed by adding an empty body `{}` to my HTTP request, so it's not a major issue. However, I'd expect empty bodies to result in the empty value for my requests. Is that a strange expectation?

Basically, I want this to happen on the server side before my request handler is invoked, in Go-pseudo:
```go
if r.ContentLength == 0 {
  r.Body = bytes.NewBuffer("{}")
}

// rest of the Connect magic

**Comment by joshcarp** [comment]
I think that it's semantically correct to say that an empty string is _not_ valid json: `""` should always show as invalid with `content-type: application/json`.
Adding on `{}` to the body would also be adding json encoding specific logic to connect, which wouldn't be desired.

**Comment by torkelrogstad** [comment]
In that case I think the error message should be improved. It took me quite a bit of head-scratching to understand what this meant

**Comment by akshayjshah** [comment]
Improving the error message is definitely doable!

I'm particularly reluctant to implicitly treat `""` and `"{}"` identically because it diverges from `protojson`, and is likely to introduce incompatibilities with other gRPC implementations. (This is a pretty soft objection, but I'd rather be conservative.)

**Comment by mattrobenolt** [comment]
imo this is pretty easy to solve in your own tiny bit of middleware. I agree, it's technically invalid and incorrect. If someone using connect-go wants to deviate, they have the tools to do so.

Something like:

```go
func EnsureBody(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        if r.ContentLength == 0 {
            r.Body = bytes.NewBuffer("{}")
            r.ContentLength = 2
        }
        next.ServeHTTP(w, r)
    })
}

var mux http.Handler = http.NewServeMux()
mux = EnsureBody(mux)
```

something like that, entirely untested, etc, but this is simple enough to implement your logic for your use case.
