### ISSUE TITLE
Service option for Connect HTTP path

### ISSUE THREAD

**Issue by dgroux** [bufbuild/connect-go#468]
I have not been able to figure out how to change the HTTP path for a Connect service method.

I think it would be best if we could specify the path in the service specification, as does GRPC gateway.
[google.api.http](https://github.com/grpc-ecosystem/grpc-gateway#usage)

A custom path option specific to Buf Connect, something like:

`
service YourService {
 rpc Echo(StringMessage) returns (StringMessage) {
   option (connect.http.path) = "/v1/example/echo";
  }
}
`

It would be very useful to be able to support custom paths in my use case where the default (and case-sensitive)"/{service}/{method}" is not sufficient.

**Comment by akshayjshah** [comment]
Hey Dylan - I can understand why you might want this, but it's not something we're willing to put into Connect itself right now. I have two significant reservations about this:

* The path is part of the gRPC and Connect protocols; customizable paths will break gRPC clients and clients using v1 of the Connect protocol.
* Custom paths also degrade the ability of middle boxes (like Envoy and other RPC-aware proxies) to collect stats and make routing decisions. More generally, custom paths prevent any system from tying HTTP traffic to an RPC service & method without a compiled, up-to-date copy of the schema, which tends to be difficult at scale. (Unless you're using Buf's schema registry, of course 😄 )

For now, your best bet is to use a combination of redirects on the server side and raw `NewClient` usage on the client side. I'm going to close this to clearly indicate that we're not planning to work on it in the foreseeable future.
