### ISSUE TITLE
Update protoc-gen-connect-go to preserve more comments

### ISSUE THREAD

**Issue by pkwarren** [bufbuild/connect-go#470]
**Is your feature request related to a problem? Please describe.**
When converting .proto files to .go files, some comments for the file and the package are lost. A recent update to grpc-go fixed a similar problem, and protobuf-go has addressed this for some time.

**Describe the solution you'd like**
Preserve more comments from the original .proto file in the generated .go source.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by akshayjshah** [comment]
@VoyTechnology we've already merged support for this, so your issue should be solved in the next release!
