### ISSUE TITLE
Generate constants for full method names

### ISSUE THREAD

**Issue by pkwarren** [bufbuild/connect-go#471]
**Is your feature request related to a problem? Please describe.**
It would be convenient in some cases to have access to the full method name for each method. Previous attempts to add this data required separate plugins: https://github.com/bufbuild/plugins/issues/264

**Describe the solution you'd like**
Add the full method name as a constant in the generated .go code.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bufdev** [comment]
I'd like to make sure this is necessary before we potentially pollute the generated code.

**Comment by akshayjshah** [comment]
> I'd like to make sure this is necessary before we potentially pollute the generated code.

Ack. This comes up pretty often (#326, #383, Slack, in person with https://github.com/cuebox) - the most common use case is exempting some RPCs from logging or auth middleware without hard-coding a string literal. The [best available workaround](https://github.com/bufbuild/connect-go/issues/326#issuecomment-1354089305) is not very good, so IMO this is worthwhile.

**Comment by bufdev** [comment]
Ok
