### ISSUE TITLE
stream type constants other than StreamTypeUnary are untyped numerics

### ISSUE THREAD

**Issue by jhump** [bufbuild/connect-go#485]
Here's the Go code that defines these constants: https://github.com/bufbuild/connect-go/blob/main/connect.go#L48-L53
```go
const (
	StreamTypeUnary  StreamType = 0b00
	StreamTypeClient            = 0b01
	StreamTypeServer            = 0b10
	StreamTypeBidi              = StreamTypeClient | StreamTypeServer
)
```

I have a very strong suspicion that the last three were meant to be of type `StreamType`, just like the first one. However, they explicitly state a value but no type, which means they are actually untyped numeric constants. The only time when the type can be omitted and it "inherits" from the previous declaration is when both type _and value_ are omitted.

Sadly, changing this is technically a breaking change, since any code that might be referring to these and expecting them to implicitly be converted to an `int` (for example) would encounter a compilation error if we "fix" this. However, given that this seems like an obvious accident, maybe there's room for entertaining a fix?

```diff
 const (
 	StreamTypeUnary  StreamType = 0b00
-	StreamTypeClient            = 0b01
-	StreamTypeServer            = 0b10
+	StreamTypeClient StreamType = 0b01
+	StreamTypeServer StreamType = 0b10
	StreamTypeBidi              = StreamTypeClient | StreamTypeServer
)
```

**Comment by akshayjshah** [comment]
Yep, let's fix this. 🤦🏽
