### ISSUE TITLE
add constructor for ServerStreamForClient

### ISSUE THREAD

**Issue by terinjokes** [bufbuild/connect-go#507]
**Is your feature request related to a problem? Please describe.**
A powerful feature of grpc is making function calls that traverse the network seem like local function calls. Client call sites do not need to think about where the server is or the protocol to communicate with it. This also allows system architects to design systems where parts can be divided in the future, but where services might be implemented within the same process. Where the service is implemented, potentially remote, potentially local, could possibly be determined (and changed) at runtime.

It does not seem to be possible to implement local versions of rpc services with connect-go as there is no constructor for `ServerStreamForClient`, a type used in the generated client interface for stream responses.

**Describe the solution you'd like**
It should be possible for teams to implement the generated connect-go interfaces for their services.

**Describe alternatives you've considered**
A similar request was made in #458, but more related to mocking in tests. The proposed solution of creating a full http server is not a sufficient alternative to local implementations, as there is still significant overhead in the network IO, framing, and (un)marshalling on both sides.

**Additional context**
By way of contrast, in the following code blocks I show a (admittedly simplified and contrived) example for how teams might implement local implementations in grpc for the following service:

```protoc
syntax = "proto3";

package service;

service FeatureServer {
    rpc ListFeatures(ListFeaturesRequest) returns (stream ListFeaturesResponse) {}
}

message ListFeaturesRequest {
    string state = 1;
}

message ListFeaturesResponse {
    string name = 1;
}
```

This service streams features that are in some state.

```go
type LocalFeatureService struct {
	localFeatures []string
}

func (fs *LocalFeatureService) ListFeatures(ctx context.Context, in *service.ListFeaturesRequest, opts ...grpc.CallOption) (service.FeatureServer_ListFeaturesClient, error) {
	features := make([]string, len(fs.localFeatures))
	copy(features, fs.localFeatures)

	return &listFeaturesResponse{
		features: features,
	}, nil
}

type listFeaturesResponse struct {
	grpc.ClientStream
	features []string
}

func (r *listFeaturesResponse) Recv() (*service.ListFeaturesResponse, error) {
	if len(r.features) == 0 {
		return nil, io.EOF
	}

	var feature string
	feature, r.features = r.features[0], r.features[1:]
	return &service.ListFeaturesResponse{
		Name: feature,
	}, nil
}
```

It could then be used, with the decision for local or remote made at runtime

```go
func main() {
	var FeatureService service.FeatureServerClient
	switch FeatureImplementation {
	case "local":
		FeatureService = &LocalFeatureService{
			localFeatures: []string{"catan", "ticket to ride", "7 wonders"},
		}
	default:
		conn, err := grpc.Dial("feature.example.svc.cluster.local:8080")
		if err != nil {
			panic(err)
		}

		FeatureService = service.NewFeatureServerClient(conn)
	}

	stream, err := FeatureService.ListFeatures(context.Background(), &service.ListFeaturesRequest{State: "enabled"})
	if err != nil {
		panic(err)
	}

	for {
		feature, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			panic(err)
		}

		fmt.Printf("feature: %s\n", feature.Name)
	}
}

```

```
feature: catan
feature: ticket to ride
feature: 7 wonders
```

When the `LocalFeatureService` implementation is being used, no calls into the network stack are required, no are there any unnecessary framing or marshaling steps.

**Comment by akshayjshah** [comment]
Thanks for the detailed feature request, @terinjokes! I agree that it's often useful to code against an RPC interface, even if the functionality is implemented in-process. For unary calls, `connect-go` already makes this pretty simple: the generated server and client APIs are identical, so the server-side implementation is usable as a client. (This is the primary reason `connect-go` doesn't have per-call client and handler options.)

For anything more complex, including streaming, I think it's valuable to use a full HTTP server and client with an in-memory `net.Conn`. This has a few benefits, _particularly_ in the situation you're outlining:

* It avoids passing pointers to shared memory between components that you'd like to keep strongly separated.
* It incurs the full cost of serialization and framing, and (ideally) some artificial latency introduced in the in-memory `net.Conn`. This forces you to design APIs that aren't overly chatty.
* It properly handles all the intricacies of HTTP headers and connection management.

Would skipping the network -- but still going through marshaling and framing -- work for your use case?

**Comment by terinjokes** [comment]
Sorry, I've been on another project for the past three weeks, so your email has just been at the top of my inbox. I'll take a look at the in-memory HTTP server.
