### ISSUE TITLE
Provide the Host value to handlers

### ISSUE THREAD

**Issue by ymmt2005** [bufbuild/connect-go#513]
I wanted to use the `Host` field value of the `http.Request` in my application.
Since Go does not set `Host` header in `http.Header`, connect-go handlers cannot
access this information.

ref: https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/net/http/request.go;l=157-158

**Describe the solution you'd like**
It would be great if `connect.Request` provided the Host field value in the `http.Request`.
For example,

```go
func (MyHandler) DoSomething(ctx context.Context, req *connect.Request[pb.Request]) (*connect.Response[pb.Response], error) {
    fmt.Println(req.Host())
}
```

**Describe alternatives you've considered**
My current workaround is to wrap the HTTP handler returned by `NewXXX` generated function like:

```go
	mux := http.NewServeMux()
	p, h := myserviceconnect.NewMyServiceHandler(handler)
	h2 := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		r.Header.Set("Host", r.Host)
		h.ServeHTTP(w, r)
	})
	mux.Handle(p, h2)
```

This way, I can access the Host value from handlers with `req.Header().Get("Host")`.

**Comment by jhump** [comment]
It looks like the reverse flow is also problematic: the Go "net/http" client ignores a header key of "Host", instead requiring the caller to set the `Host` field of the `*http.Request`. But Connect clients don't have access to set this field. So in addition to currying the `request.Host` field into headers for server handlers, we should do the reverse (set the `request.Host` field _from_ headers, if set by client or interceptor) on the client side.

**Comment by emcfarlane** [comment]
@ymmt2005 fixed in a similar way to the workaround. Host is available in the request header.

**Comment by ymmt2005** [comment]
@emcfarlane Thank you so much!
