### ISSUE TITLE
How to know if a service method is idempotent

### ISSUE THREAD

**Issue by juanpmarin** [bufbuild/connect-go#514]
**Is your feature request related to a problem? Please describe.**
I'm using a connect interceptor to wrap every request with a db transaction, but I would like to start a transaction only when needed, of course I don't need a transaction for a NO_SIDE_EFFECTS idempotency level

**Describe the solution you'd like**
Being able to get the idempotency level of the method being called within an interceptor

**Comment by timostamm** [comment]
Hey Juan, this sounds like a great idea. You can get the idempotency level via [connect.Spec](https://pkg.go.dev/github.com/bufbuild/connect-go#Spec). It's available with a getter on [connect.AnyRequest](https://pkg.go.dev/github.com/bufbuild/connect-go#AnyRequest). Let us know if that works for you 🙂

**Comment by juanpmarin** [comment]
Thanks! @timostamm 

Here is the code snippet if someone ever needs it

```
if request.Spec().IdempotencyLevel == connect.IdempotencyNoSideEffects {
	return next(ctx, request)
}
```
