### ISSUE TITLE
Metadata names are not canonicalized when using Connect streaming

### ISSUE THREAD

**Issue by jchadwick-buf** [bufbuild/connect-go#524]
**Describe the bug**

Background: If you set or receive a trailer on a Connect unary or gRPC request, it will actually be sent as a header or trailer on the wire. However, in Connect streaming requests, it's embedded in JSON instead. As mentioned in the Connect documentation:

> Semantically, trailing metadata should be treated as HTTP headers: keys are case-insensitive, values for the same key can be joined with commas, and so on. _(In practice, Connect implementations typically deserialize trailing metadata into the same data structure used for HTTP headers.)_

Unfortunately, that last part is a problem. We literally `json.Unmarshal` into `http.Header`, bypassing the canonicalization that would ordinarily happen when it is parsed from MIME headers or h2, and just treating it as a typical map/JSON object. That means that in the following [Connect example](https://connect.build/docs/protocol#error-end-stream):

```json
{
  "error": {
    "code": "unavailable"
  },
  "metadata": {
    "acme-operation-cost": ["237"]
  }
}
```

...the trailer object would contain a key `acme-operation-cost`, uncanonicalized, which would make all of the case-insensitive `http.Header` accessors unable to see it. This is not the case outside of Connect streaming. It will not occur when using unary requests or gRPC streaming.

**To Reproduce**

For completeness, I made a separate demo repository showcasing the bug and how to reproduce it.

https://github.com/jchadwick-buf/connect-go-streaming-trailer-bug

**Comment by jchadwick-buf** [comment]
I explored some options to solve the problem. Using a custom type with an `UnmarshalJSON` parser (that utilizes json.Decoder.Token under the hood) turned out to be more inefficient than simply fixing the map ex-post-facto using a simple fixup loop:

```
BenchmarkHTTPHeaderDecodeSimple-10     	 1524178	       776.6 ns/op	     808 B/op	      14 allocs/op
BenchmarkHTTPHeaderDecodeComplex-10    	  278216	      4134 ns/op	    2104 B/op	      44 allocs/op
BenchmarkJSONHeaderDecodeSimple-10     	  939591	      1281 ns/op	    1864 B/op	      30 allocs/op
BenchmarkJSONHeaderDecodeComplex-10    	  129514	      9157 ns/op	    5752 B/op	     214 allocs/op
```

In particular, when using a custom decoder, the allocations skyrocket. I believe this is because allocations grow linearly with input size in the Go JSON parser, and we multiply this when we use both `UnmarshalJSON` (which has to still lex the JSON and track the state) and a nested `json.Decoder`; however, I did not look further.

This would suggest that our best bet is doing a simple fixup loop (this is the one I tested with my benchmark):

```go
for name, value := range header {
	canonical := http.CanonicalHeaderKey(name)
	if name != canonical {
		delete(header, name)
		header[canonical] = value
	}
}
```

...Although this has the potentially undesirable side-effect that names which resolve to the same canonicalization will override each-other in a non-deterministic fashion.

**Comment by akshayjshah** [comment]
😿 We should definitely fix this.

Fixing this in two passes seems fine to me. In the simple example, though, why discard values when two keys canonicalize to the same string? Seems like we could do this instead:

```go
for name, value := range header {
	canonical := http.CanonicalHeaderKey(name)
	if name != canonical {
		delete(header, name)
		header[canonical] = append(header[canonical], value...)
	}
}
```
